### ISSUE TITLE
PreviewButton.js - Incorrect (or misleading) URL in REST call

### ISSUE THREAD

**Issue by dtrimsd** [sanity-io/tutorial-speech-synthesis-editor-studio#3]
PreviewButton.js - Line 9

`const GOOGLE_TEXT_TO_SPEECH_URL = `https://texttospeech.googleapis.com/v1beta1/text:synthesize?key=${API_KEY}`;`

URL is pointing to **v1beta1** . The Text-to-Speech api has been released to production. The URL should point to **v1**.

`const GOOGLE_TEXT_TO_SPEECH_URL = `https://texttospeech.googleapis.com/v1/text:synthesize?key=${API_KEY}`;`

**Comment by kmelve** [comment]
You're correct. I've updated the code – thanks for the report!
