### ISSUE TITLE
Speak Text Button - Sanity interface - Bug/Usability

### ISSUE THREAD

**Issue by dtrimsd** [sanity-io/tutorial-speech-synthesis-editor-studio#4]
The Speak Text button provides no feedback when errors occur.

Per the JavaScript console log errors occur when the button is pushed and

1. either Title, Response, or both are empty
2. the call to the Google's text-to-speech api fails

These errors are not displayed. 

See https://youtu.be/CLPrL_8frZk for demonstration

![Speak Text Error](https://user-images.githubusercontent.com/9920123/60146538-96f0ed00-978f-11e9-8ba2-912087900e8c.png)

**Comment by kmelve** [comment]
We didn't add error handling or any "production grade" features to keep the code as simple as minimal as possible to keep the tutorial easy to follow. I'm sorry if this wasn't apparent.
