### ISSUE TITLE
Speak text button: Inconsistent interface

### ISSUE THREAD

**Issue by dtrimsd** [sanity-io/tutorial-speech-synthesis-editor-studio#5]
The **Speak text** button's color is inconsistent when compared to the **Publish** button. 

I assume the the **Publish
![Speak Text Error](https://user-images.githubusercontent.com/9920123/60146701-30200380-9790-11e9-98cf-c821b77e0a27.png)
** button is the correct color.

**Comment by kmelve** [comment]
Only the Publish button should be blue according to our style guide. This is also just a demo of functionality, and not intended as a production-ready solution. :)
